using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;
using System.Threading;

namespace FlexPipe.SourceGeneration;

[Generator]
public class PipelineContextGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("FlexPipePolyfills.g.cs", SourceText.From(PolyfillsSource, Encoding.UTF8)));

        var pipelineDefinitions = context.CompilationProvider
            .SelectMany(static (compilation, ct) => GetPipelineDefinitions(compilation, ct));

        context.RegisterSourceOutput(pipelineDefinitions, static (spc, info) =>
            spc.AddSource($"{info.ContextName}.g.cs", SourceText.From(GenerateSource(info), Encoding.UTF8)));
    }

    private static ImmutableArray<PipelineInfo> GetPipelineDefinitions(
        Compilation compilation,
        CancellationToken ct)
    {
        var interfaceSymbol = compilation.GetTypeByMetadataName("FlexPipe.IPipelineDefinition`2");
        if (interfaceSymbol is null)
            return ImmutableArray<PipelineInfo>.Empty;

        var results = ImmutableArray.CreateBuilder<PipelineInfo>();
        WalkNamespace(compilation.GlobalNamespace, interfaceSymbol, results, ct);
        return results.ToImmutable();
    }

    private static void WalkNamespace(
        INamespaceSymbol ns,
        INamedTypeSymbol interfaceSymbol,
        ImmutableArray<PipelineInfo>.Builder results,
        CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        foreach (var member in ns.GetMembers())
        {
            if (member is INamespaceSymbol childNs)
            {
                WalkNamespace(childNs, interfaceSymbol, results, ct);
                continue;
            }

            if (member is not INamedTypeSymbol typeSymbol)
                continue;

            var assemblyName = typeSymbol.ContainingAssembly?.Name ?? string.Empty;
            if (assemblyName.StartsWith("System") ||
                assemblyName.StartsWith("Microsoft") ||
                assemblyName.StartsWith("mscorlib") ||
                assemblyName.StartsWith("netstandard"))
                continue;

            foreach (var iface in typeSymbol.AllInterfaces)
            {
                if (!SymbolEqualityComparer.Default.Equals(iface.OriginalDefinition, interfaceSymbol) ||
                    iface.TypeArguments.Length != 2)
                    continue;

                var namespaceName = typeSymbol.ContainingNamespace.IsGlobalNamespace
                    ? null
                    : typeSymbol.ContainingNamespace.ToDisplayString();

                results.Add(new PipelineInfo(
                    namespaceName,
                    DeriveContextName(typeSymbol.Name),
                    iface.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    iface.TypeArguments[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
                break;
            }
        }
    }

    private static string DeriveContextName(string pipelineName)
    {
        const string suffix = "Pipeline";
        return pipelineName.EndsWith(suffix)
            ? pipelineName.Substring(0, pipelineName.Length - suffix.Length) + "Context"
            : pipelineName + "Context";
    }

    private static string GenerateSource(PipelineInfo info)
    {
        var classDecl = $@"    public partial class {info.ContextName}
        : global::FlexPipe.IPipelineContext<{info.InputType}, {info.OutputType}>
    {{
        public required {info.InputType} Input {{ get; init; }}

        public {info.OutputType} Output {{ get; set; }} = default!;

        private readonly global::System.Collections.Generic.List<global::System.Exception> _errors = [];

        public bool IsFailed => _errors.Count > 0;

        public global::System.Collections.Generic.IReadOnlyList<global::System.Exception> Errors => _errors;

        public void Fail(string error)
        {{
#if NET6_0_OR_GREATER
            var ex = new global::System.Exception(error);
            global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(ex);
            _errors.Add(ex);
#else
            try {{ throw new global::System.Exception(error); }}
            catch (global::System.Exception ex) {{ _errors.Add(ex); }}
#endif
        }}

        public void Fail(global::System.Exception exception) => _errors.Add(exception);
    }}";

        return info.Namespace is null
            ? classDecl
            : $"namespace {info.Namespace}\n{{\n{classDecl}\n}}";
    }

    private const string PolyfillsSource = """
        // <auto-generated/>
        #if !NET5_0_OR_GREATER
        namespace System.Runtime.CompilerServices
        {
            internal static class IsExternalInit { }
        }
        #endif

        #if !NET7_0_OR_GREATER
        namespace System.Runtime.CompilerServices
        {
            [global::System.AttributeUsage(
                global::System.AttributeTargets.Class |
                global::System.AttributeTargets.Struct |
                global::System.AttributeTargets.Field |
                global::System.AttributeTargets.Property,
                AllowMultiple = false,
                Inherited = false)]
            internal sealed class RequiredMemberAttribute : global::System.Attribute { }

            [global::System.AttributeUsage(
                global::System.AttributeTargets.All,
                AllowMultiple = true,
                Inherited = false)]
            internal sealed class CompilerFeatureRequiredAttribute : global::System.Attribute
            {
                public CompilerFeatureRequiredAttribute(string featureName)
                {
                    FeatureName = featureName;
                }
                public string FeatureName { get; }
                public bool IsOptional { get; set; }
            }
        }

        namespace System.Diagnostics.CodeAnalysis
        {
            [global::System.AttributeUsage(
                global::System.AttributeTargets.Constructor,
                AllowMultiple = false,
                Inherited = false)]
            internal sealed class SetsRequiredMembersAttribute : global::System.Attribute { }
        }
        #endif
        """;

    private record PipelineInfo(
        string? Namespace,
        string ContextName,
        string InputType,
        string OutputType);
}
